# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_0.xci
# IP: The module: 'fir_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i0/fir_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i0 || ORIG_REF_NAME==fir_c_addsub_v12_0_i0} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i1/fir_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i1 || ORIG_REF_NAME==fir_c_addsub_v12_0_i1} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i10/fir_c_addsub_v12_0_i10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i10 || ORIG_REF_NAME==fir_c_addsub_v12_0_i10} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i2/fir_c_addsub_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i2 || ORIG_REF_NAME==fir_c_addsub_v12_0_i2} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i3/fir_c_addsub_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i3 || ORIG_REF_NAME==fir_c_addsub_v12_0_i3} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i4/fir_c_addsub_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i4 || ORIG_REF_NAME==fir_c_addsub_v12_0_i4} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i5/fir_c_addsub_v12_0_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i5 || ORIG_REF_NAME==fir_c_addsub_v12_0_i5} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i6/fir_c_addsub_v12_0_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i6 || ORIG_REF_NAME==fir_c_addsub_v12_0_i6} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i7/fir_c_addsub_v12_0_i7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i7 || ORIG_REF_NAME==fir_c_addsub_v12_0_i7} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i8/fir_c_addsub_v12_0_i8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i8 || ORIG_REF_NAME==fir_c_addsub_v12_0_i8} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i9/fir_c_addsub_v12_0_i9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i9 || ORIG_REF_NAME==fir_c_addsub_v12_0_i9} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_mult_gen_v12_0_i0/fir_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_mult_gen_v12_0_i0 || ORIG_REF_NAME==fir_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/constrs/fir.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_0.xci
# IP: The module: 'fir_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i0/fir_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i0 || ORIG_REF_NAME==fir_c_addsub_v12_0_i0} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i1/fir_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i1 || ORIG_REF_NAME==fir_c_addsub_v12_0_i1} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i10/fir_c_addsub_v12_0_i10.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i10 || ORIG_REF_NAME==fir_c_addsub_v12_0_i10} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i2/fir_c_addsub_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i2 || ORIG_REF_NAME==fir_c_addsub_v12_0_i2} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i3/fir_c_addsub_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i3 || ORIG_REF_NAME==fir_c_addsub_v12_0_i3} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i4/fir_c_addsub_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i4 || ORIG_REF_NAME==fir_c_addsub_v12_0_i4} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i5/fir_c_addsub_v12_0_i5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i5 || ORIG_REF_NAME==fir_c_addsub_v12_0_i5} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i6/fir_c_addsub_v12_0_i6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i6 || ORIG_REF_NAME==fir_c_addsub_v12_0_i6} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i7/fir_c_addsub_v12_0_i7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i7 || ORIG_REF_NAME==fir_c_addsub_v12_0_i7} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i8/fir_c_addsub_v12_0_i8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i8 || ORIG_REF_NAME==fir_c_addsub_v12_0_i8} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_c_addsub_v12_0_i9/fir_c_addsub_v12_0_i9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_c_addsub_v12_0_i9 || ORIG_REF_NAME==fir_c_addsub_v12_0_i9} -quiet] -quiet

# IP: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_mult_gen_v12_0_i0/fir_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_mult_gen_v12_0_i0 || ORIG_REF_NAME==fir_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: g:/a_max/max_xilinx/max/System_Generator/FIR/FIR3/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/constrs/fir.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
