# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/ip/fir_bd_fir_1_0/fir_bd_fir_1_0.xci
# IP: The module: 'fir_bd_fir_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/ip/fir_bd_fir_1_0/fir_fir_compiler_v7_2_i0/fir_fir_compiler_v7_2_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/ip/fir_bd_fir_1_0/fir_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/ip/fir_bd_fir_1_0/constrs/fir.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_bd_fir_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/ip/fir_bd_fir_1_0/fir_bd_fir_1_0.xci
# IP: The module: 'fir_bd_fir_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/ip/fir_bd_fir_1_0/fir_fir_compiler_v7_2_i0/fir_fir_compiler_v7_2_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/ip/fir_bd_fir_1_0/fir_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/ip/fir_bd_fir_1_0/constrs/fir.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_bd_fir_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
