# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Bilibili_FPGA/N2_Project/VIVADO/demo_v1/hdl_netlist/demo_sg.srcs/sources_1/ip/demo_sg_c_counter_binary_v12_0_i0/demo_sg_c_counter_binary_v12_0_i0.xci
# IP: The module: 'demo_sg_c_counter_binary_v12_0_i0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Bilibili_FPGA/N2_Project/VIVADO/demo_v1/hdl_netlist/demo_sg.srcs/sources_1/ip/demo_sg_c_counter_binary_v12_0_i0/demo_sg_c_counter_binary_v12_0_i0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo_sg_c_counter_binary_v12_0_i0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Bilibili_FPGA/N2_Project/VIVADO/demo_v1/hdl_netlist/demo_sg.srcs/sources_1/ip/demo_sg_c_counter_binary_v12_0_i0/demo_sg_c_counter_binary_v12_0_i0.xci
# IP: The module: 'demo_sg_c_counter_binary_v12_0_i0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Bilibili_FPGA/N2_Project/VIVADO/demo_v1/hdl_netlist/demo_sg.srcs/sources_1/ip/demo_sg_c_counter_binary_v12_0_i0/demo_sg_c_counter_binary_v12_0_i0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo_sg_c_counter_binary_v12_0_i0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
