# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/a_max/max/xlinx/opendv/1_hello_world/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_processing_system7_0_0/hello_word_processing_system7_0_0.xci
# IP: The module: 'hello_word_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/a_max/max/xlinx/opendv/1_hello_world/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_processing_system7_0_0/hello_word_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_word_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/a_max/max/xlinx/opendv/1_hello_world/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_processing_system7_0_0/hello_word_processing_system7_0_0.xci
# IP: The module: 'hello_word_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/a_max/max/xlinx/opendv/1_hello_world/hello_word.srcs/sources_1/bd/hello_word/ip/hello_word_processing_system7_0_0/hello_word_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_word_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
