# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param netlist.enableMultipleFileLines 1
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -id {BD 41-759}  -new_severity {INFO} 
set_msg_config  -id {BD 41-759}  -new_severity {CRITICAL WARNING} 
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.cache/wt [current_project]
set_property parent.project_path C:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/imports/hdl/fir_bd_wrapper.v
  C:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/imports/sysgen/fir_mod.v
}
add_files C:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/fir_bd.bd
set_property used_in_implementation false [get_files -all c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/ip/fir_bd_fir_1_0/fir_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/ip/fir_bd_fir_1_0/constrs/fir.xdc]
set_property used_in_implementation false [get_files -all C:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/bd/fir_bd/fir_bd_ooc.xdc]

read_ip -quiet c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_0.xci
set_property used_in_implementation false [get_files -all c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/fir_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/sources_1/ip/fir_0/constrs/fir.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/constrs_1/imports/sysgen/fir_clock.xdc
set_property used_in_implementation false [get_files C:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/constrs_1/imports/sysgen/fir_clock.xdc]

read_xdc C:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/constrs_1/imports/sysgen/fir.xdc
set_property used_in_implementation false [get_files C:/a_max/max_xilinx/max/System_Generator/FIR/par/ip_catalog/fir.srcs/constrs_1/imports/sysgen/fir.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fir_bd_wrapper -part xc7z010clg400-1 -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fir_bd_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fir_bd_wrapper_utilization_synth.rpt -pb fir_bd_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
