# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5.xci
# IP: The module: 'system_rst_ps7_0_100M_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_100M_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5.xci
# IP: The module: 'system_rst_ps7_0_100M_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
