# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/fir_clock.xdc

# XDC: imports/sysgen/fir.xdc

# Block Designs: bd/fir_bd/fir_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_bd || ORIG_REF_NAME==fir_bd} -quiet] -quiet

# IP: bd/fir_bd/ip/fir_bd_fir_1_0/fir_bd_fir_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_bd_fir_1_0 || ORIG_REF_NAME==fir_bd_fir_1_0} -quiet] -quiet

# XDC: bd/fir_bd/fir_bd_ooc.xdc
