# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/system_axi_smc_5.xci
# IP: The module: 'system_axi_smc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/bd_4723.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_0/bd_4723_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_1/bd_4723_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_2/bd_4723_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_3/bd_4723_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_4/bd_4723_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_5/bd_4723_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_6/bd_4723_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_7/bd_4723_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_8/bd_4723_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_9/bd_4723_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_10/bd_4723_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_11/bd_4723_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_12/bd_4723_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_13/bd_4723_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_14/bd_4723_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_15/bd_4723_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_16/bd_4723_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_17/bd_4723_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_18/bd_4723_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_19/bd_4723_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_20/bd_4723_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_21/bd_4723_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_22/bd_4723_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_23/bd_4723_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_24/bd_4723_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_25/bd_4723_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_26/bd_4723_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_1/bd_4723_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_1/bd_4723_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_2/bd_4723_arsw_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_3/bd_4723_rsw_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_4/bd_4723_awsw_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_5/bd_4723_wsw_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_6/bd_4723_bsw_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_10/bd_4723_s00a2s_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_11/bd_4723_sarn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_12/bd_4723_srn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_16/bd_4723_s01a2s_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_17/bd_4723_sawn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_18/bd_4723_swn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_19/bd_4723_sbn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_20/bd_4723_m00s2a_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_21/bd_4723_m00arn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_22/bd_4723_m00rn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_23/bd_4723_m00awn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_24/bd_4723_m00wn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_25/bd_4723_m00bn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/system_axi_smc_5.xci
# IP: The module: 'system_axi_smc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/bd_4723.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_0/bd_4723_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_1/bd_4723_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_2/bd_4723_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_3/bd_4723_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_4/bd_4723_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_5/bd_4723_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_6/bd_4723_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_7/bd_4723_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_8/bd_4723_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_9/bd_4723_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_10/bd_4723_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_11/bd_4723_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_12/bd_4723_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_13/bd_4723_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_14/bd_4723_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_15/bd_4723_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_16/bd_4723_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_17/bd_4723_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_18/bd_4723_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_19/bd_4723_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_20/bd_4723_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_21/bd_4723_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_22/bd_4723_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_23/bd_4723_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_24/bd_4723_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_25/bd_4723_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_26/bd_4723_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_1/bd_4723_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_1/bd_4723_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_2/bd_4723_arsw_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_3/bd_4723_rsw_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_4/bd_4723_awsw_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_5/bd_4723_wsw_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_6/bd_4723_bsw_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_10/bd_4723_s00a2s_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_11/bd_4723_sarn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_12/bd_4723_srn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_16/bd_4723_s01a2s_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_17/bd_4723_sawn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_18/bd_4723_swn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_19/bd_4723_sbn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_20/bd_4723_m00s2a_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_21/bd_4723_m00arn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_22/bd_4723_m00rn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_23/bd_4723_m00awn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_24/bd_4723_m00wn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/bd_0/ip/ip_25/bd_4723_m00bn_0_ooc.xdc

# XDC: f:/ZYNQ/Embedded_System/ov7725_lcd/ov7725_lcd.srcs/sources_1/bd/system/ip/system_axi_smc_5/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
