# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Bilibili_FPGA/N4_Project/VIVADO/hdl_netlist/fir_filter.srcs/sources_1/ip/fir_filter_c_counter_binary_v12_0_i0/fir_filter_c_counter_binary_v12_0_i0.xci
# IP: The module: 'fir_filter_c_counter_binary_v12_0_i0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Bilibili_FPGA/N4_Project/VIVADO/hdl_netlist/fir_filter.srcs/sources_1/ip/fir_filter_c_counter_binary_v12_0_i0/fir_filter_c_counter_binary_v12_0_i0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_c_counter_binary_v12_0_i0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Bilibili_FPGA/N4_Project/VIVADO/hdl_netlist/fir_filter.srcs/sources_1/ip/fir_filter_c_counter_binary_v12_0_i0/fir_filter_c_counter_binary_v12_0_i0.xci
# IP: The module: 'fir_filter_c_counter_binary_v12_0_i0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Bilibili_FPGA/N4_Project/VIVADO/hdl_netlist/fir_filter.srcs/sources_1/ip/fir_filter_c_counter_binary_v12_0_i0/fir_filter_c_counter_binary_v12_0_i0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_c_counter_binary_v12_0_i0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
