# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Navigator/Nav_code_7020__PS/ov7725_hdmi_sobel_1013/ov7725_hdmi_sobel.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0.xci
# IP: The module: 'design_1_v_vid_in_axi4s_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Navigator/Nav_code_7020__PS/ov7725_hdmi_sobel_1013/ov7725_hdmi_sobel.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Navigator/Nav_code_7020__PS/ov7725_hdmi_sobel_1013/ov7725_hdmi_sobel.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/Navigator/Nav_code_7020__PS/ov7725_hdmi_sobel_1013/ov7725_hdmi_sobel.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0.xci
# IP: The module: 'design_1_v_vid_in_axi4s_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Navigator/Nav_code_7020__PS/ov7725_hdmi_sobel_1013/ov7725_hdmi_sobel.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Navigator/Nav_code_7020__PS/ov7725_hdmi_sobel_1013/ov7725_hdmi_sobel.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
